config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show]
  end

  # Defines the root path route ("/")
  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, class_name: 'Post'

  after_save :update_comments_counter

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, class_name: 'Post'

  after_save :update_likes_counter

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :likes, class_name: 'Like', foreign_key: 'post_id'
  has_many :comments, class_name: 'Comment', foreign_key: 'post_id'

  after_save :update_posts_counter

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_comments
    comments.last(5)
  end

  def update_posts_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, class_name: 'Post', foreign_key: 'author_id'
  has_many :likes, class_name: 'Like', foreign_key: 'author_id'
  has_many :comments, class_name: 'Comment', foreign_key: 'author_id'

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.last(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    User.first
  end
end

app/controllers/post_controller.rb
class PostsController < ApplicationController
  def show
    puts params
  end

  def index
    puts params
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
    render action: '_empty_list' if @posts.empty?
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
    @user = current_user
  end

  def get_user_name(author_id)
    User.find(author_id).name
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to user_post_url(current_user, @post), notice: 'Post was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :text, :comments_counter, :likes_counter)
  end

  helper_method :get_user_name
end

app/controllers/user_controller.rb
class UsersController < ApplicationRecord
  def show
    puts params
  end

  def index
    puts params
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_comments_tile.html.erb
<% stylesheet_link_tag 'posts/comments_tile' %>

<div class="comments-tile">
  <ul>
    <% comments.each do |comment| %>
      <li>
        <p class="commenter"><%= get_user_name(comment.author_id) %>:</p>
        <p><%= comment.text %></p>
      </li>
    <% end %>
  </ul>
  <% if comments.length == 0 %>
    <p>No Comments yet</p>
  <% end %>
</div>

app/views/posts/_empty_list.html.erb
<% stylesheet_link_tag 'posts/index' %>

<div id="all-posts-page" class="content">
  <%= render 'users/user_tile', user: @user %>
  <h2>There are no posts in this list yet.</h2>
</div>

app/views/posts/_expanded_post_tile.html.erb
<% stylesheet_link_tag 'posts/expanded_post_tile' %>

<div class="expanded-post-tile">
  <div class="post-data">
    <h2>Post #<%= post.id %> by <%= post.author.name %></h2>
    <div class="comments-likes">
      <p>Comments <%= post.comments_counter || 0 %></p>
      <p>Likes <%= post.likes_counter || 0 %></p>
    </div>
  </div>
  <p><%= post.text %></p>
</div>

app/views/posts/_post_tile.html.erb
<% stylesheet_link_tag 'posts/post_tile' %>

<div class="post-tile">
  <h2>Post #<%= post.id %></h2>
  <p class="post-text"><%= post.text %></p>
  <div class="comments-likes">
    <p>Comments <%= post.comments_counter || 0 %></p>
    <p>Likes <%= post.likes_counter || 0 %></p>
  </div>
</div>

app/views/posts/index.html.erb
<% stylesheet_link_tag 'posts/index' %>

<div id="all-posts-page" class="content">
  <%= render 'users/user_tile', user: @user %>
  <ul>
    <% @posts.each do |post| %>
      <li>
        <%= link_to user_post_path(@user, post) do %>
          <%= render 'posts/post_tile', post: post, expanded: false %>
        <% end %>
        <%= render 'posts/comments_tile', comments: post.recent_comments %>
      </li>
    <% end %>
  </ul>
</div>

app/views/posts/show.html.erb
<% stylesheet_link_tag 'posts/show' %>

<div id="post-page" class="content">
  <%= render 'posts/expanded_post_tile', post: @post %>
  <%= render 'posts/comments_tile', comments: @post.comments %>
</div>

app/views/users/_user_tile.erb
<% stylesheet_link_tag 'users/user_tile' %>
<%= link_to user do %>
  <div class="user-tile">
    <div class="user-image">
      <img src="<%= user.photo %>" alt="Profile Picture">
    </div>
    <div class="user-details">
      <h1><%= user.name %></h1>
      <p>Number of Posts: <%= user.posts_counter || 0 %></p>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<% stylesheet_link_tag 'users/index' %>

<div id="users-list-page" class="content">
  <ul>
    <% @users.each do |user| %>
      <li>
        <%= render 'users/user_tile', user: user %>
      </li>
    <% end %>
  </ul>
</div>

app/views/users/show.html.erb
<% stylesheet_link_tag 'users/show' %>

<div id="user-details-page" class="content">
  <%= render 'users/user_tile', user: @user %>
  <div id="bio">
    <p id="bio-tag">Bio</p>
    <p><%= @user.bio %></p>
  </div>
  <ul>
    <% @user.recent_posts.each do |post| %>
      <li>
        <%= link_to user_post_path(@user, post) do %>
          <%= render 'posts/post_tile', post: post, expanded: false %>
        <% end %>
      </li>
    <% end %>
  </ul>
  <div id="all-posts-button">
    <%= link_to user_posts_path(@user) do %>
      <button id="see-all-posts">See all posts</button>
    <% end %>
  </div>
</div>